# 汇丰 HSBC HK（含其 App 依赖的埋点 / 反欺诈 / 客服 SDK 域名）
DOMAIN-SUFFIX,hsbc.com.hk
DOMAIN,cdnbc.wup.hsbc.com.hk
DOMAIN,hsbc.edge.sdk.awswaf.com
DOMAIN,c-hsbc.lytics.io
DOMAIN,mobile.eum-appdynamics.com
DOMAIN,tags.tiqcdn.com
DOMAIN,cdn.optimizely.com
DOMAIN,log-58144bf0.we-stats.com
DOMAIN-SUFFIX,tealiumiq.com
DOMAIN-SUFFIX,online-metrix.net
DOMAIN-SUFFIX,cloud1.vv1865.com
DOMAIN-SUFFIX,liveperson.net
DOMAIN-SUFFIX,lpsnmedia.net
DOMAIN-SUFFIX,hsbc.com
